name: portfolio
description: A flutter app to showcase my work
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  dio: ^5.3.2
  go_router: ^10.1.0
  meta: ^1.9.1
  flutter_adaptive_ui: ^0.8.0+1
  flutter_screenutil: ^5.9.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: dosis
      fonts:
        - asset: assets/fonts/dosis.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto_slab.ttf
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir_regular.ttf
    - family: iransans
      fonts:
        - asset: assets/fonts/iransans.ttf
    - family: nastaligh
      fonts:
        - asset: assets/fonts/nastaliq_regular.ttf
