name: portfolio
description: A flutter app to showcase my work
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  get_it: ^7.6.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  dio: ^5.3.2
  go_router: ^10.1.0
  meta: ^1.9.1
  flutter_adaptive_ui: ^0.8.0+1
  flutter_screenutil: ^5.9.0
  flutter_web_plugins:
    sdk: flutter
  x_framework: 
    git:
      url: https://github.com/codingwithsaeed/x_framework.git
      ref: '4148646'
  gradient_borders: ^1.0.0
  flutter_adaptive_scaffold: ^0.1.7+1
  auto_size_text: ^3.0.0
  mobx: ^2.2.1
  flutter_mobx: ^2.1.0+1
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: dosis
      fonts:
        - asset: assets/fonts/dosis.ttf
    - family: sahel
      fonts:
        - asset: assets/fonts/sahel.ttf
        - asset: assets/fonts/sahel_bold.ttf
          weight: 700 
        - asset: assets/fonts/sahel_black.ttf
          weight: 900
